use std::fs;
use std::path::PathBuf;
use syn::{parse_file, Fields, Item, Type};

/// Read-only struct shapes to export to TypeScript. The list is hand-curated
/// in build.rs so that command inputs (NewCustomer, NewOrder, ...) are NOT
/// accidentally exported — only the rows that actually cross the IPC
/// boundary on read.
const EXPORTED_STRUCTS: &[(&str, &str)] = &[
    ("repos::customers::Customer", "src/repos/customers.rs"),
    ("repos::filaments::Filament", "src/repos/filaments.rs"),
    ("repos::printers::Printer", "src/repos/printers.rs"),
    ("repos::orders::Order", "src/repos/orders.rs"),
    ("repos::quote_items::QuoteItem", "src/repos/quote_items.rs"),
    ("repos::settings::Settings", "src/repos/settings.rs"),
    ("commands::dashboard::DashboardData", "src/commands/dashboard.rs"),
    ("commands::dashboard::Kpis", "src/commands/dashboard.rs"),
    ("commands::dashboard::DailyTotal", "src/commands/dashboard.rs"),
    ("commands::dashboard::UpcomingOrder", "src/commands/dashboard.rs"),
    ("commands::dashboard::LowStockFilament", "src/commands/dashboard.rs"),
    ("commands::dashboard::OverdueOrder", "src/commands/dashboard.rs"),
];

/// Hand-curated narrowings for fields that are typed as `String` in Rust
/// but are in fact string enums on the SQL side. The build script will
/// emit the listed union instead of `string` for these.
///
/// Format: `RustTypeName.field_name` => "union literal".
const ENUM_FIELDS: &[(&str, &str, &str)] = &[
    // Material
    (
        "Filament",
        "material",
        "'PLA' | 'PETG' | 'ABS' | 'TPU' | 'ASA' | 'NYLON' | 'PC' | 'OTHER'",
    ),
    // Printer status
    ("Printer", "status", "'active' | 'maintenance' | 'retired'"),
    // Order status
    (
        "Order",
        "status",
        "'draft' | 'in_produzione' | 'completato' | 'consegnato' | 'annullato'",
    ),
    // Settings.id is literally 1 (CHECK constraint) — see schema.sql
    ("Settings", "id", "1"),
];

fn main() {
    tauri_build::build();

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out_dir = manifest_dir
        .parent()
        .expect("workspace root")
        .join("src/lib/db-types.generated.ts");

    // Collect all narrowing literals so we can emit named type aliases.
    let mut type_aliases: Vec<(String, String)> = Vec::new();
    for (parent, field, lit) in ENUM_FIELDS {
        // Alias name = the field type, e.g. "Filament.material" -> "FilamentMaterial"
        // Skip the Settings.id marker (no need to alias the literal `1`).
        if *parent == "Settings" {
            continue;
        }
        // Camel-case the field name and prefix with the parent struct.
        let alias = format!(
            "{}{}",
            parent,
            field
                .split('_')
                .map(|w| {
                    let mut c = w.chars();
                    match c.next() {
                        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                        None => String::new(),
                    }
                })
                .collect::<String>()
        );
        type_aliases.push((alias, lit.to_string()));
    }

    let mut buf = String::new();
    buf.push_str("// AUTO-GENERATED by src-tauri/build.rs — DO NOT EDIT\n");
    buf.push_str("// Regenerate by running `cargo build` (the build script\n");
    buf.push_str("// re-runs when any of the listed .rs files change).\n");
    buf.push_str("//\n");
    buf.push_str("// Source of truth: the #[derive(Serialize)] structs in\n");
    buf.push_str("// src-tauri/src/repos/*.rs and src-tauri/src/commands/dashboard.rs.\n\n");
    for (name, lit) in &type_aliases {
        buf.push_str(&format!("export type {name} = {lit}\n"));
    }
    buf.push('\n');

    for (rust_path, rel) in EXPORTED_STRUCTS {
        let full = manifest_dir.join(rel);
        let src = fs::read_to_string(&full)
            .unwrap_or_else(|e| panic!("read {}: {e}", full.display()));
        let ast = parse_file(&src).expect("parse rust file");

        let struct_name = rust_path.split("::").last().unwrap();
        let s = find_struct(&ast, struct_name)
            .unwrap_or_else(|| panic!("struct {struct_name} not found in {rel}"));

        buf.push_str(&format!("export interface {} {{\n", struct_name));
        if let Fields::Named(named) = &s.fields {
            for f in &named.named {
                let name = f.ident.as_ref().expect("named field").to_string();
                let ty = type_to_ts(&f.ty, struct_name, &name);
                buf.push_str(&format!("  {name}: {ty}\n"));
            }
        } else {
            panic!("{}: only named-field structs supported", struct_name);
        }
        buf.push_str("}\n\n");
    }

    fs::write(&out_dir, buf).expect("write db-types.generated.ts");
    println!("cargo:rerun-if-changed=src/repos/customers.rs");
    println!("cargo:rerun-if-changed=src/repos/filaments.rs");
    println!("cargo:rerun-if-changed=src/repos/printers.rs");
    println!("cargo:rerun-if-changed=src/repos/orders.rs");
    println!("cargo:rerun-if-changed=src/repos/quote_items.rs");
    println!("cargo:rerun-if-changed=src/repos/settings.rs");
    println!("cargo:rerun-if-changed=src/commands/dashboard.rs");
}

fn find_struct<'a>(ast: &'a syn::File, name: &str) -> Option<&'a syn::ItemStruct> {
    ast.items.iter().find_map(|i| match i {
        Item::Struct(s) if s.ident == name => Some(s),
        _ => None,
    })
}

fn type_to_ts(ty: &Type, parent: &str, field: &str) -> String {
    // Check for an enum narrowing first.
    for (p, f, lit) in ENUM_FIELDS {
        if *p == parent && *f == field {
            return lit.to_string();
        }
    }

    match ty {
        Type::Path(p) => {
            let seg = p.path.segments.last().expect("type path");
            let id = seg.ident.to_string();
            match id.as_str() {
                "String" => "string".into(),
                "bool" => "boolean".into(),
                "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "isize" | "usize" => {
                    "number".into()
                }
                "f32" | "f64" => "number".into(),
                "Option" => {
                    // Option<T> -> T | null
                    if let syn::PathArguments::AngleBracketed(args) = &seg.arguments {
                        if let Some(syn::GenericArgument::Type(inner)) = args.args.first() {
                            return format!("{} | null", type_to_ts(inner, parent, field));
                        }
                    }
                    "unknown | null".into()
                }
                "Vec" => {
                    if let syn::PathArguments::AngleBracketed(args) = &seg.arguments {
                        if let Some(syn::GenericArgument::Type(inner)) = args.args.first() {
                            return format!("{}[]", type_to_ts(inner, parent, field));
                        }
                    }
                    "unknown[]".into()
                }
                // Foreign type (chrono, uuid, etc.) — fall back to string for safety.
                other => {
                    if is_known_primitive(other) {
                        other.to_lowercase()
                    } else {
                        // Likely a struct in our crate — refer to it by name.
                        other.to_string()
                    }
                }
            }
        }
        _ => "unknown".into(),
    }
}

fn is_known_primitive(s: &str) -> bool {
    matches!(
        s,
        "String" | "bool"
            | "i8" | "i16" | "i32" | "i64"
            | "u8" | "u16" | "u32" | "u64"
            | "f32" | "f64"
            | "usize" | "isize"
    )
}
