// Re-export of the auto-generated types. The actual TypeScript
// declarations live in `db-types.generated.ts`, which is produced by
// `src-tauri/build.rs` from the `#[derive(Serialize)]` structs in
// `src-tauri/src/repos/*.rs` and `src-tauri/src/commands/dashboard.rs`.
//
// Hand-written narrowings (FilamentMaterial, PrinterStatus, OrderStatus)
// are derived from the ENUM_FIELDS table in build.rs.
//
// Do not edit this file — make changes in the Rust structs and re-run
// `cargo build` to regenerate.
export * from './db-types.generated'
