// AUTO-GENERATED by src-tauri/build.rs — DO NOT EDIT
// Regenerate by running `cargo build` (the build script
// re-runs when any of the listed .rs files change).
//
// Source of truth: the #[derive(Serialize)] structs in
// src-tauri/src/repos/*.rs and src-tauri/src/commands/dashboard.rs.

export type FilamentMaterial = 'PLA' | 'PETG' | 'ABS' | 'TPU' | 'ASA' | 'NYLON' | 'PC' | 'OTHER'
export type PrinterStatus = 'active' | 'maintenance' | 'retired'
export type OrderStatus = 'draft' | 'in_produzione' | 'completato' | 'consegnato' | 'annullato'

export interface Customer {
  id: string
  name: string
  email: string
  phone: string | null
  address: string | null
  vat_number: string | null
  notes: string | null
  created_at: string
  deleted_at: string | null
}

export interface Filament {
  id: string
  brand: string
  material: 'PLA' | 'PETG' | 'ABS' | 'TPU' | 'ASA' | 'NYLON' | 'PC' | 'OTHER'
  color: string | null
  diameter: number
  density: number | null
  price_per_kg: number
  stock_grams: number
  low_stock_threshold: number
  created_at: string
  deleted_at: string | null
}

export interface Printer {
  id: string
  name: string
  model: string | null
  build_volume_x: number | null
  build_volume_y: number | null
  build_volume_z: number | null
  status: 'active' | 'maintenance' | 'retired'
  notes: string | null
  created_at: string
  deleted_at: string | null
}

export interface Order {
  id: string
  customer_id: string
  status: 'draft' | 'in_produzione' | 'completato' | 'consegnato' | 'annullato'
  notes: string | null
  margin_percent: number
  apply_vat: boolean
  created_at: string
  updated_at: string
  deleted_at: string | null
}

export interface QuoteItem {
  id: string
  order_id: string
  description: string
  quantity: number
  time_hours: number
  material_grams: number
  filament_id: string | null
  post_processing_cost: number
  sort_order: number
  created_at: string
}

export interface Settings {
  id: 1
  default_hourly_rate: number
  default_margin_percent: number
  currency: string
  vat_rate: number
  updated_at: string
}

export interface StockAuditEntry {
  id: string
  filament_id: string
  delta_grams: number
  stock_after: number
  reason: string
  order_id: string | null
  user_note: string | null
  created_at: string
}

export interface DashboardData {
  kpis: Kpis
  revenue_30d: DailyTotal[]
  upcoming: UpcomingOrder[]
  low_stock: LowStockFilament[]
  overdue: OverdueOrder[]
}

export interface Kpis {
  open_orders: number
  month_revenue: number
  total_customers: number
  kg_consumed_month: number
  low_stock_filaments: number
  overdue_orders: number
}

export interface DailyTotal {
  date: string
  total: number
}

export interface UpcomingOrder {
  id: string
  customer_id: string
  customer_name: string
  status: string
  created_at: string
  total: number
}

export interface LowStockFilament {
  id: string
  brand: string
  material: string
  color: string | null
  stock_grams: number
  low_stock_threshold: number
}

export interface OverdueOrder {
  id: string
  customer_id: string
  customer_name: string
  status: string
  created_at: string
  days_old: number
}

